# Generated by Django 5.1.3 on 2024-11-23 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabricante',
            name='uniforme_colegio',
        ),
    ]
