# Generated by Django 5.1.3 on 2024-11-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
